import { render, screen, fireEvent, waitFor, cleanup } from '@testing-library/react'
import { vi, describe, it, expect, beforeEach } from 'vitest'
const { uploadMock, activeSummaryMock, submitTextMock, submitTextImageMock, alertMock, confirmMock } = vi.hoisted(() => ({ uploadMock: vi.fn(), activeSummaryMock: vi.fn(), submitTextMock: vi.fn(), submitTextImageMock: vi.fn(), alertMock: vi.fn(), confirmMock: vi.fn(async () => true) }))
vi.mock('../components/AppDialogProvider',()=>({useAppDialog:()=>({alert:alertMock,confirm:confirmMock,choose:vi.fn(async()=>null)})}))
vi.mock('../api',()=>{const ok=data=>Promise.resolve({data});return{promptOptimizeAPI:{optimize:vi.fn(),optimizeStream:vi.fn()},uploadAPI:{upload:uploadMock},generateAPI:{submitText:submitTextMock,submitTextImage:submitTextImageMock},taskAPI:{activeSummary:activeSummaryMock,list:vi.fn(async()=>({data:[]})),get:vi.fn(async()=>({data:{task_id:'t1',status:'processing',progress:10,result_urls:[],error:null,params:{},prompt:'',type:'text'}})),getByClientRequestId:vi.fn(async()=>({data:{task_id:'t1',status:'processing',progress:10,result_urls:[],error:null,params:{},prompt:'',type:'text'}})),retry:vi.fn(async()=>({data:{}})),delete:vi.fn(async()=>({data:{}})),batchDelete:vi.fn(async()=>({data:{deleted:0,deleted_ids:[],failed:[]}}))},imageAPI:{list:vi.fn(async()=>({data:{images:[]}})),extend:vi.fn(async()=>({data:{success_count:0,skipped_count:0,failed_count:0,total_cost:0,points:100}})),delete:vi.fn(async()=>({data:{}})),batchDelete:vi.fn(async()=>({data:{deleted:0,deleted_filenames:[],failed:[]}}))},squareAPI:{share:vi.fn(async()=>({data:{id:1}})),unshare:vi.fn(async()=>({data:{}})),my:vi.fn(async()=>ok({images:[]})),list:vi.fn(async()=>ok({images:[],total:0})),like:vi.fn(async()=>ok({}))},adminAPI:{users:vi.fn(async()=>({data:{users:[],total:0}}))},pointsAPI:{balance:vi.fn(async()=>ok({points:100})),checkinStatus:vi.fn(async()=>ok({checked_in_today:false})),checkin:vi.fn(async()=>ok({points:110,message:'ok'}))},configAPI:{get:vi.fn(async()=>ok({home_page_size:24,square_page_size:20,points_cost_per_generation:10,points_cost_per_optimize:10,points_cost_per_optimize_refine:20,points_cost_per_image_extend:2}))},promptAPI:{listPublic:vi.fn(async()=>ok({prompts:[]})),categories:vi.fn(async()=>ok({categories:[]}))},notificationAPI:{unreadCount:vi.fn(async()=>ok({count:0})),list:vi.fn(async()=>ok({items:[]})),markRead:vi.fn(async()=>ok({})),markAllRead:vi.fn(async()=>ok({})),clearRead:vi.fn(async()=>ok({deleted:0}))},announcementAPI:{getUnread:vi.fn(async()=>ok({items:[]})),list:vi.fn(async()=>ok({items:[],total:0})),markRead:vi.fn(async()=>ok({}))}}})
import ChatInput from '../components/ChatInput'
import ChatPage from '../pages/ChatPage'
import { LayoutModeProvider } from '../LayoutModeContext'
import { ThemeProvider } from '../ThemeContext'
import { MemoryRouter } from 'react-router-dom'
beforeEach(()=>{cleanup();localStorage.clear();localStorage.setItem('user',JSON.stringify({id:1,user_id:1,username:'tester',nickname:'tester',points:100,is_admin:false}));uploadMock.mockReset();activeSummaryMock.mockReset();submitTextMock.mockReset();submitTextImageMock.mockReset();alertMock.mockReset();confirmMock.mockReset();confirmMock.mockResolvedValue(true);activeSummaryMock.mockResolvedValue({data:{active_count:0,global_limit:20,available_slots:20}});submitTextMock.mockResolvedValue({data:{task_id:'task-text',status:'processing',message:'ok'}});submitTextImageMock.mockResolvedValue({data:{task_id:'task-image',status:'processing',message:'ok'}});window.fetch=vi.fn(async(url)=>({ok:true,status:200,headers:new Headers({'content-type':'image/png'}),blob:async()=>new Blob(['img'],{type:'image/png'}),json:async()=>({}),text:async()=>'',url}))})
describe('reference upload flow',()=>{it('blocks submit on failed upload and allows submit after delete',async()=>{const onSubmit=vi.fn(async()=>true);uploadMock.mockRejectedValueOnce(new Error('上传失败'));const {container}=render(<ChatInput onSubmit={onSubmit} loading={false} requestCost={10} optimizeCost={10} refineOptimizeCost={20} />);fireEvent.change(container.querySelector('input[type="file"]'),{target:{files:[new File(['img'],'fail.png',{type:'image/png'})]}});await waitFor(()=>expect(screen.getByText('存在上传失败的参考图，请删除后重新添加')).toBeInTheDocument());fireEvent.change(screen.getByPlaceholderText('把脑洞变成画✨ 支持文生图+图生图'),{target:{value:'test prompt'}});expect(screen.getByTitle('生成')).toBeDisabled();const deleteBtn=container.querySelector('.absolute.-top-1.-right-1');fireEvent.click(deleteBtn);await waitFor(()=>expect(screen.queryByText('存在上传失败的参考图，请删除后重新添加')).not.toBeInTheDocument());expect(screen.getByTitle('生成')).not.toBeDisabled();expect(onSubmit).not.toHaveBeenCalled()});it('submits only preuploaded success images',async()=>{uploadMock.mockResolvedValue({data:{url:'https://cdn.example/ref.png',storage_name:'uploads/ref.png'}});const {container}=render(<MemoryRouter><ThemeProvider><LayoutModeProvider><ChatPage /></LayoutModeProvider></ThemeProvider></MemoryRouter>);fireEvent.change(await screen.findByPlaceholderText('把脑洞变成画✨ 支持文生图+图生图'),{target:{value:'prompt'}});fireEvent.change(container.querySelector('input[type="file"]'),{target:{files:[new File(['img'],'ok.png',{type:'image/png'})]}});await waitFor(()=>expect(uploadMock).toHaveBeenCalledTimes(1));fireEvent.click(screen.getByTitle('生成'));await screen.findByText('批量生成');fireEvent.click(screen.getByText('确认生成'));await waitFor(()=>expect(submitTextImageMock).toHaveBeenCalledTimes(1));expect(submitTextImageMock.mock.calls[0][0].image_urls).toEqual(['https://cdn.example/ref.png']);expect(submitTextImageMock.mock.calls[0][0].local_image_urls).toEqual(['uploads/ref.png']);expect(uploadMock).toHaveBeenCalledTimes(1)})})
